name: ci

on: [ workflow_dispatch, push, pull_request ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Setup python
        uses: actions/setup-python@main
        with:
          python-version: 3.12
      - name: Install Tools
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install pylint
          python3 -m pip install mypy
      - name: Test
        run: |
          find compiler -iname "*.py" | grep -v -e "__init__.py" | xargs -L 1 mypy --strict
          python3 -m unittest compiler/tests.py
